# Generated by Django 5.2 on 2025-04-28 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('calories_per_100g', models.DecimalField(decimal_places=2, max_digits=6)),
                ('price_per_100g', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('protein_per_100g', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('fat_per_100g', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('carbs_per_100g', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FoodEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_in_grams', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodplaner.food')),
            ],
        ),
    ]
