# Generated by Django 5.2 on 2025-05-06 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodplaner', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodentry',
            name='amount_in_grams',
        ),
        migrations.RemoveField(
            model_name='foodentry',
            name='food',
        ),
        migrations.CreateModel(
            name='FoodEntryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_in_grams', models.DecimalField(decimal_places=2, max_digits=5)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodplaner.food')),
                ('food_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodplaner.foodentry')),
            ],
        ),
        migrations.AddField(
            model_name='foodentry',
            name='foods',
            field=models.ManyToManyField(through='foodplaner.FoodEntryItem', to='foodplaner.food'),
        ),
    ]
