# Generated by Django 5.2 on 2025-05-07 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodplaner', '0002_remove_foodentry_amount_in_grams_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodentry',
            name='date',
            field=models.DateField(unique=True),
        ),
    ]
